### PR TITLE
Workaround for @spawnat problem.Avoid overflow in mapreduce tests

### LINKED ISSUE #46: test suite failing on 0.5 julia master
The test suite is failing for me on julia master
```
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+1030 (2015-10-30 11:53 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit ee584e8* (0 days old master)
|__/                   |  x86_64-apple-darwin14.5.0

```

output - https://gist.github.com/amitmurthy/20c9d263f1dc95e26323

Anybody else seeing this?

### PR DESCRIPTION
**Pull request by amitmurthy**
Closes #46.

Some change recently on master with `localize_vars` is causing problems with certain uses of `@spawnat` and `@async`. I have not been able to isolate the problem yet.

This is a workaround for the problem.

### CODE REVIEW

**Comment by amitmurthy** [comment]
cc: @andreasnoack ,@malmaud (since you have been looking at `localize_vars` recently)

File: src/DistributedArrays.jl [hunk 1]
```diff
@@ -544,12 +548,12 @@ end
 
 function mapreducedim_between!(f, op, R::DArray, A::DArray, region)
     @sync for p in procs(R)
-        @spawnat p begin
+        @async remotecall_wait((f, op, R, A, region) -> begin
```
Comment (andreasnoack) [inline src/DistributedArrays.jl]: Isn't this a good candite for a `do` block?

Comment (amitmurthy) [inline src/DistributedArrays.jl]: Yes.

**Comment by andreasnoack** [comment]
Thanks for fixing this. I have no idea about why it was necessary.

**Comment by amitmurthy** [comment]
Me neither. The bigger issue that needs to be fixed is the root cause in Julia master.
